name: Release Doctor

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-24.04
    if: github.repository == 'ejc3/terraform-provider-cloudflare'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check release environment
        run: |
          bash ./scripts/check-release-environment
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
